# Generated by Django 5.1.3 on 2024-11-22 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='media_file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'mp4', 'mov'])]),
        ),
    ]
