# Generated by Django 5.1.3 on 2024-11-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_mediapost_delete_mediaupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediapost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mediapost',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='mediapost',
            name='video',
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='uploads/media/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='uploads.mediapost')),
            ],
        ),
    ]
